##配置端口好
#server:
#  port: 80
#
#
##配置日志格式
##  root: debug 齐全
##  root: warn 简洁
##  root: info 默认
#logging:
#  level:
#    root: info
#
#
#lesson: StringBoot
#
#enterprise:
#  name: study
#  age: 12
#  tel: 123456
#  subject:
#    - 学习
#    - 唱歌
#    - 跳舞
